version: "3.8"

services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "443:443"
    volumes:
      - ./web:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    secrets:
      - ssl_crt
      - ssl_key

  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    depends_on:
      - mariadb
    volumes:
      - ./web:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    secrets:
      - db_user_password
      - wp_user_password
      - wp_admin_password

  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    volumes:
      - database:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    secrets:
      - db_user_password
      - db_admin_password

networks:
  inception:

volumes:
  database:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/database
      o: bind

secrets:
  ssl_crt:
    file: ./secrets/server.crt
  ssl_key:
    file: ./secrets/server.key
  db_user_password:
    file: ./secrets/db_user_password.txt
  db_admin_password:
    file: ./secrets/db_admin_password.txt
  wp_user_password:
    file: ./secrets/wp_user_password.txt
  wp_admin_password:
    file: ./secrets/wp_admin_password.txt
